import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create my first next app',
  description: 'Generated by create my first next app',
}


const  RootLayout = (props: {children: React.ReactNode, team: React.ReactNode}) => {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>fuck you</h1>
        </header>
        {props.children}
        {props.team}
      </body>
    </html>
  )
}


export default RootLayout